package tui

import (
	_ "embed"
	"strings"

	"github.com/charmbracelet/lipgloss"
)

// mascotCompactRaw and mascotFullRaw are ASCII/braille-art renders of
// Optimus Prime supplied by the project owner (not generated by an AI model
// or reproduced from Hasbro source art). The compact version powers the
// idle empty-conversation state and /logo; the full version gets the
// one-time startup-banner reveal.
//
//go:embed assets/optimus_compact.txt
var mascotCompactRaw string

//go:embed assets/optimus_full.txt
var mascotFullRaw string

func mascotCompactLines() []string {
	return strings.Split(strings.TrimRight(mascotCompactRaw, "\n"), "\n")
}

func mascotFullLines() []string {
	return strings.Split(strings.TrimRight(mascotFullRaw, "\n"), "\n")
}

// mascotWidth returns the rune width of a rectangular art block. Every line
// in both assets is the same width by construction, so the first line's
// width stands for the whole block.
func mascotWidth(lines []string) int {
	if len(lines) == 0 {
		return 0
	}
	return len([]rune(lines[0]))
}

// gradientColor picks a color from gradient proportional to col's position
// across [0, width), giving a smooth left-to-right sweep.
func gradientColor(gradient []string, col, width int) lipgloss.Color {
	if width <= 1 {
		return lipgloss.Color(gradient[0])
	}
	idx := col * (len(gradient) - 1) / (width - 1)
	if idx >= len(gradient) {
		idx = len(gradient) - 1
	}
	return lipgloss.Color(gradient[idx])
}

// renderIdleMascot centers the fully-colorized compact mascot within a
// width x height box — the empty-conversation placeholder shown before the
// first message is sent, so the mascot stays part of the CLI beyond the
// startup banner instead of just vanishing into a blank screen.
func renderIdleMascot(width, height int) string {
	lines := mascotCompactLines()
	content := renderArt(lines, mascotWidth(lines), bannerGradient)
	return lipgloss.Place(width, height, lipgloss.Center, lipgloss.Center, content)
}

// renderArt colorizes lines left-to-right with gradient, revealing only the
// first revealCols runes of each line (pass a revealCols at or beyond the
// block's width to render it in full, e.g. for /logo's static output).
func renderArt(lines []string, revealCols int, gradient []string) string {
	var b strings.Builder
	for i, line := range lines {
		if i > 0 {
			b.WriteByte('\n')
		}
		runes := []rune(line)
		width := len(runes)
		limit := revealCols
		if limit > width {
			limit = width
		}
		for c := 0; c < limit; c++ {
			ch := runes[c]
			if ch == ' ' || ch == '⠀' { // U+2800 = blank braille pattern
				b.WriteRune(ch)
				continue
			}
			color := gradientColor(gradient, c, width)
			b.WriteString(lipgloss.NewStyle().Foreground(color).Render(string(ch)))
		}
	}
	return b.String()
}
